# Generated by Django 3.1 on 2021-08-25 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='Users.connectionstate'),
        ),
    ]
